version: '3'

services:

  web-site:
    build: .

    # command: python manage.py runserver 0.0.0.0:8000 # already exist in Dockerfile conf

    volumes:
      - .:/kilo

    ports:
      - '8080:8000'

    restart: always

    entrypoint: /kilo/entrypoint.sh